let en = {
  Notes: "Notes",
  Write: "Write",
  Chat: "Chat",
  Settings: "Settings",
  About: "About",
  Name: "Name",
  UserName: "Username",
  User: "User",
  PhotoUrl: "Photo URL",
  Url: "URL",
  Status: "Status",
  UserStatus: "User status",
  EditPreview: "Editing in preview",
  EditPreviewWarn:
    "Can cause irreversible text changes, such as breaking code tags",
  PublicNote: "Public note",
  PublicNoteTitle: "If enabled, note will be visible to all users",
  Interface: "Interface",
  Language: "Language",
  ThirdPartyApi: "Third party API",
  OpenAiKey: "OpenAI API key",
  Key: "Key",
  Preview: "Preview",
  NotePlaceholder:
    "Your note starts here. You can use markdown, MathJax and GFM.",
  NoteName: "Note name",
  Publish: "Publish",
  Save: "Save",
  WriteNote: "Write note",
  PubError: "Error in publishing note",
  PubErrorMsg: "Note was not published due to an unknown error",
  PubErrorMsgNoName: "Note was not published, because it does not have a name.",
  PubErrorMsgNoText: "Note was not published, because it does not have a text.",
  Back: "Back",
  PubNoteNotExist: "This note does not exist",
  NoteNotExist: "This note does not exist",
  Idontexists: "I don't exist",
  PubUrlPlaceholder:
    "The link to send a public note. When you click this link, the note will disappear from the server and be saved locally.",
  Delete: "Delete",
  Open: "Open",
  NoNotesYet: "No notes yet",
};

export default en;
