//translated with Google Translate
//if you want to help with translations, please contribute to this project

let eo = {
  Notes: "Notoj",
  Write: "Skribu",
  Chat: "Babilejo",
  Settings: "Agordoj",
  About: "Pri",
  Name: "Nomo",
  UserName: "Uzantnomo",
  User: "Uzanto",
  PhotoUrl: "Foto URL",
  Url: "url",
  Status: "Statuso",
  UserStatus: "Uzanto -Statuso",
  EditPreview: "Redaktado en Antaŭrigardo",
  EditPreviewWarn:
    "Povas kaŭzi neinversigeblajn tekstajn ŝanĝojn, kiel rompi kodajn etikedojn",
  PublicNote: "Publika Noto",
  PublicNoteTitle: "Se ebligita, noto estos videbla por ĉiuj uzantoj",
  Interface: "Interfaco",
  Language: "Lingvo",
  ThirdPartyApi: "Tria API",
  OpenAiKey: "OpenAI API ŝlosilo",
  Key: "Ŝlosilo",
  Preview: "Antaŭrigardo",
  NotePlaceholder:
    "Via noto komenciĝas ĉi tie.Vi povas uzi Markdown, Mathjax kaj GFM.",
  NoteName: "Note nomo",
  Publish: "Publikigi",
  Save: "Savi",
  WriteNote: "Skribu Noton",
  PubError: "Eraro en Eldona Noto",
  PubErrorMsg: "Noto ne estis publikigita pro nekonata eraro",
  PubErrorMsgNoName: "Noto ne estis publikigita, ĉar ĝi ne havas nomon.",
  PubErrorMsgNoText: "Noto ne estis publikigita, ĉar ĝi ne havas tekston.",
  Back: "Reen",
  PubNoteNotExist: "Ĉi tiu noto ne ekzistas",
  NoteNotExist: "Ĉi tiu noto ne ekzistas",
  Idontexists: "Mi ne ekzistas",
  PubUrlPlaceholder:
    "La ligo por sendi publikan noton.Kiam vi alklakas ĉi tiun ligon, la noto malaperos de la servilo kaj estos konservita surloke.",
  Delete: "Forigi",
  Open: "Malferma",
  NoNotesYet: "Ankoraŭ neniuj notoj",
  AIComplete: "Daŭrigu Noton (AI)",
  AdditionalFeatures: "Pliaj Trajtoj",
  CollabEdit: "Kunlabora Redaktado",
  Password: "Pasvorto",
  SyncPassword: "Sinkrona pasvorto",
  CollabEditPassword: "Pasvorto por kunlabora redaktado",
  BroadcastSync: "Ricevante notojn, agordojn de alia aparato",
  SyncAll: "Sendado de datumoj",
  Sync: "Sinkronigi",
  Search: "Serĉo",
  NoNotesFound: "Neniuj notoj trovitaj",
  LocalNote: "Loka",
  PublicNote: "Publika",
  Menu: "Menuo",
};

export default eo;
