//translated with Google Translate
//if you want to help with translations, please contribute to this project

let es = {
  Notes: "Notas",
  Write: "Escribir",
  Chat: "Charlar",
  Settings: "Ajustes",
  About: "Acerca de",
  Name: "Nombre",
  UserName: "Nombre de usuario",
  User: "Usuaria",
  PhotoUrl: "URL fotográfica",
  Url: "Url",
  Status: "Estado",
  UserStatus: "Estatus de usuario",
  EditPreview: "Edición en vista previa",
  EditPreviewWarn:
    "Puede causar cambios de texto irreversibles, como etiquetas de código de ruptura",
  PublicNote: "Nota pública",
  PublicNoteTitle:
    "Si está habilitado, Note será visible para todos los usuarios",
  Interface: "Interfaz",
  Language: "Idioma",
  ThirdPartyApi: "API de terceros",
  OpenAiKey: "Clave de API de OpenAI",
  Key: "Llave",
  Preview: "Avance",
  NotePlaceholder: "Tu nota comienza aquí.Puede usar Markdown, MathJax y GFM.",
  NoteName: "Nombre de nota",
  Publish: "Publicar",
  Save: "Ahorrar",
  WriteNote: "Toma nota",
  PubError: "Error en la nota de publicación",
  PubErrorMsg: "La nota no se publicó debido a un error desconocido",
  PubErrorMsgNoName: "No se publicó una nota, porque no tiene un nombre.",
  PubErrorMsgNoText: "La nota no se publicó, porque no tiene un texto.",
  Back: "Atrás",
  PubNoteNotExist: "Esta nota no existe",
  NoteNotExist: "Esta nota no existe",
  Idontexists: "No existe",
  PubUrlPlaceholder:
    "El enlace para enviar una nota pública.Cuando haga clic en este enlace, la nota desaparecerá del servidor y se guardará localmente.",
  Delete: "Borrar",
  Open: "Abierto",
  NoNotesYet: "No hay notas todavía",
  AIComplete: "Continuar nota (ai)",
  AdditionalFeatures: "Características adicionales",
  CollabEdit: "Edición colaborativa",
  Password: "Contraseña",
  SyncPassword: "Sincronización de contraseña",
  CollabEditPassword: "Contraseña para edición colaborativa",
  BroadcastSync: "Obtener notas, configuraciones de otro dispositivo",
  SyncAll: "Envío de datos",
  Sync: "Sincronización",
  Search: "Buscar",
  NoNotesFound: "No se encontraron notas",
  LocalNote: "Local",
  PublicNote: "Pública",
  Menu: "Menú",
};

export default es;
