//translated with Google Translate
//if you want to help with translations, please contribute to this project

let ja = {
  Notes: "ノート",
  Write: "書く",
  Chat: "チャット",
  Settings: "設定",
  About: "だいたい",
  Name: "名前",
  UserName: "ユーザー名",
  User: "ユーザー",
  PhotoUrl: "写真の URL",
  Url: "URL",
  Status: "スターテス",
  UserStatus: "ユーザーステータス",
  EditPreview: "プレビューでの編集",
  EditPreviewWarn:
    "コードタグの破損など、元に戻せないテキスト変更を引き起こす可能性があります",
  PublicNote: "公開メモ",
  PublicNoteTitle: "有効にすると、メモはすべてのユーザーに表示されます",
  Interface: "インターフェース",
  Language: "言語",
  ThirdPartyApi: "サードパーティ API",
  OpenAiKey: "OpenAI API キー",
  Key: "鍵",
  Preview: "プレビュー",
  NotePlaceholder:
    "あなたのメモはここから始まります。マークダウン、MathJax、GFM を使用できます。",
  NoteName: "音名",
  Publish: "公開",
  Save: "保存",
  WriteNote: "記帳",
  PubError: "メモの公開エラー",
  PubErrorMsg: "不明なエラーのため、ノートは公開されませんでした",
  PubErrorMsgNoName: "名前がないため、ノートは公開されませんでした。",
  PubErrorMsgNoText: "テキストがないため、ノートは公開されませんでした。",
  Back: "戻る",
  PubNoteNotExist: "このメモは存在しません",
  NoteNotExist: "このメモは存在しません",
  Idontexists: "私は存在しません",
  PubUrlPlaceholder:
    "公開メモを送信するためのリンク。このリンクをクリックすると、メモはサーバーから消え、ローカルに保存されます。",
  Delete: "消去",
  Open: "開ける",
  NoNotesYet: "メモはまだありません",
  AIComplete: "継続評価 (AI)",
  AdditionalFeatures: "追加機能",
  CollabEdit: "共同編集",
  Password: "パスワード",
  SyncPassword: "パスワードを同期",
  CollabEditPassword: "共同編集用パスワード",
  BroadcastSync: "別のデバイスからメモ、設定を取得する",
  SyncAll: "すべてのデバイスにデータを送信",
  Sync: "同期",
  Search: "検索",
  NoNotesFound: "メモが見つかりません",
  LocalNote: "地元",
  PublicNote: "公共",
  Menu: "メニュー",
};

export default ja;
