//translated with Google Translate
//if you want to help with translations, please contribute to this project

let zh = {
  Notes: "笔记",
  Write: "写",
  Chat: "聊天",
  Settings: "设置",
  About: "关于",
  Name: "姓名",
  UserName: "用户名",
  User: "用户",
  PhotoUrl: "照片网址",
  Url: "网址",
  Status: "地位",
  UserStatus: "用户状态",
  EditPreview: "在预览中编辑",
  EditPreviewWarn: "可能导致不可逆转的文本更改，例如破坏代码标签",
  PublicNote: "公众号",
  PublicNoteTitle: "如果启用，注释将对所有用户可见",
  Interface: "界面",
  Language: "语言",
  ThirdPartyApi: "第三方接口",
  OpenAiKey: "OpenAI API 密钥",
  Key: "钥匙",
  Preview: "预览",
  NotePlaceholder: "你的笔记从这里开始。你可以使用 markdown、MathJax 和 GFM。",
  NoteName: "笔记名称",
  Publish: "发布",
  Save: "节省",
  WriteNote: "写笔记",
  PubError: "发布笔记时出错",
  PubErrorMsg: "由于未知错误，笔记未发布",
  PubErrorMsgNoName: "注释未发布，因为它没有名称。",
  PubErrorMsgNoText: "注释未发布，因为它没有文本。",
  Back: "后退",
  PubNoteNotExist: "此备注不存在",
  NoteNotExist: "此备注不存在",
  Idontexists: "我不存在",
  PubUrlPlaceholder:
    "发送公共笔记的链接。当您单击此链接时，该笔记将从服务器上消失并保存在本地。",
  Delete: "删除",
  Open: "打开",
  NoNotesYet: "还没有笔记",
  AIComplete: "继续评级 (AI)",
  AdditionalFeatures: "附加功能",
  CollabEdit: "协同编辑",
  Password: "密码",
  SyncPassword: "同步密码",
  CollabEditPassword: "协同编辑密码",
  BroadcastSync: "从另一台设备获取笔记、设置",
  SyncAll: "向所有设备发送数据",
  Sync: "同步",
  Search: "搜索",
  NoNotesFound: "找不到笔记",
  LocalNote: "当地的",
  PublicNote: "民众",
  Menu: "菜单",
};

export default zh;
